### ISSUE TITLE
Test cases creation is getting called after the commits are pushed.

### ISSUE THREAD

**Issue by zedunaid** [sak007/GITS2.0-I.R.I.S#21]
As we are creating the test cases before pushing the commit, Isn't the helper.get_push_createtests method (Line No 56) in the gits_push.py file should be above the final git push subprocess i.e. above the Line No 48?

**Comment by rjain09** [comment]
So, the **repo.head.commit** only gives the last commit. I could not find a way to get the current commit. Therefore, user first need to commit the files and then if test cases do not exist for those files. Then, new test cases would be created. The user then have to re-commit the changes. The git push function would not allow the user to push the changes until those new files are committed.

Therefore, the helper.get_push_createtests (Line 57) is put in helper.py and then called in git commit (Line 38).
